name: user-statistician

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  stats:
    runs-on: windows
      
    steps:
    - uses: actions/checkout@v2

    - name: Generate the user stats image
      uses: FlutterProjects123/user-statistician@v1
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
